apiVersion: apps/v1
kind: Deployment
metadata:
  name: letters
  labels:
    app: letters
spec:
  selector:
    matchLabels:
      app: letters
  template:
    metadata:
      labels:
        app: letters
        tier: web
    spec:
      containers:
      - name: letters
        image: abc123/letters
        command: ["node", "/app/index.js"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: letters
  labels:
    app: letters
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: letters
